---
extends:
  - airbnb-base
  - plugin:import/warnings

env:
  browser: 1

plugins:
  - dependencies

settings:
  import/resolver: webpack

rules:
  no-console: off
  import/no-extraneous-dependencies: off
  object-curly-newline:
    - error
    - ImportDeclaration:
        minProperties: 1
        multiline: true
        consistent: true
      ObjectExpression:
        consistent: true
        minProperties: 3

parserOptions:
  parser: babel-eslint
